import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-[#dbe8cc]">
      <body 
      className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-[#dbe8cc]`}>
        <header className="pt-10 fixed top-0 left-0 right-0 z-50 ">
          <div className="flex flex-row px-20 ">
            <div className="basis-1/3 ">
              <a href="/" 
                className="transition delay-50 duration-300 ease-in-out
                bg-[#c5d4b3] text-[#8f9e7f] hover:bg-[#8f9e7f] hover:text-white font-bold px-4 py-2 rounded">
                Home
              </a>
              <a href="/motionEventsDashboard" 
                className="transition delay-50 duration-300 ease-in-out
                bg-[#c5d4b3] text-[#8f9e7f] hover:bg-[#8f9e7f] hover:text-white font-bold px-4 py-2 rounded">
                Database
              </a>
              <a href="/webcam" 
                className="transition delay-50 duration-300 ease-in-out
                bg-[#c5d4b3] text-[#8f9e7f] hover:bg-[#8f9e7f] hover:text-white font-bold px-4 py-2 rounded">
                Webcam
              </a>
            </div> 
          </div>
        </header>

        <div className="flex">  
          <div className="size-14 flex-none"></div>  
          <div className="size-14 grow p-4">
              <div className="size-14 flex-none"></div>  
              <main className="rounded-lg p-4 bg-[#c5d4b3] border-white border-2">
                {children}
              </main>
              
            </div>  
          <div className="size-14 flex-none"></div>
        </div>
      </body>
    </html>
  );
}
