import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="pt-10 fixed top-0 left-0 right-0 z-50 bg-white shadow-md">
          <div className="flex flex-row px-10">
            <div className="basis-1/3">
              <a href="/" 
                className="border border-blue-500 text-blue-500 hover:bg-blue-500 hover:text-white px-4 py-2 rounded">
                Home
              </a>
              <a href="/motionEventsDashboard" 
                className="border border-blue-500 text-blue-500 hover:bg-blue-500 hover:text-white px-4 py-2 rounded">
                Database
              </a>
              <a href="/page" 
                className="border border-blue-500 text-blue-500 hover:bg-blue-500 hover:text-white px-4 py-2 rounded">
                Webcam
              </a>
            </div> 
          </div>
        </header>

        <main className="pt-20">
          {children}
        </main>
      </body>
    </html>
  );
}
